#!/bin/sh /etc/rc.common

START=98

USE_PROCD=1
NAME=bc-turris-demo
PROG=/root/bigclown/bc-turris-demo.py

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}

stop() {
	service_stop "$PROG"
}

reload() {
	service_reload "$PROG"
}

